/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cicd;

public class App {

    public static void main(String[] args) {
        SumCalculator sumCalculator = new SumCalculator();
        System.out.println( "the number is " + sumCalculator.sum(3));

    }
}
